# Algebra 1

In [1]:
# It's generally good practice to import all required modules at the top of the script!
import sympy as sym
import numpy as np
from IPython.display import display, Math

## 1 Solving for x

In [2]:
x = sym.symbols('x')

# the expression we want to solve is 2x+4=9
expr = 2*x + 4 -9

sym.solve(expr,x)

[5/2]

In [3]:
# make it look a bit nicer

sol = sym.solve(expr,x)

display('The solution to %s is %g'%(expr,sol[0]))

# or
display(Math('\\text{The solution to }%s\\text{ is x=}%g' %(sym.latex(expr),sol[0])))

'The solution to 2*x - 5 is 2.5'

<IPython.core.display.Math object>

In [4]:
# can input the equation directly into the solve function
sym.solve(x**2 - 4,x)

[-2, 2]

In [5]:
# notice the solution is stored as a list, with one solution per element
sol = sym.solve(x**2 - 4,x)

print( type(sol) )
print( len(sol) )

<class 'list'>
2


In [6]:
# we can print them all out:
for i in range(0,len(sol)):
    print('Solution #' + str(i+1) + ' is ' + str(sol[i]))


Solution #1 is -2
Solution #2 is 2


In [7]:
y = sym.symbols('y')

expr = x/4 - x*y + 5

print( "Solved for x: " + str(sym.solve(expr,x)[0]) )
print( "Solved for y: " + str(sym.solve(expr,y)) )


Solved for x: 20/(4*y - 1)
Solved for y: [(x + 20)/(4*x)]


### 1.1 Exercises

In [8]:
# 1)
# simplify and solve for q
q = sym.symbols('q')
eq = 3*q + 4/q + 3 - 5*q - 1/q - 1

display(Math(sym.latex(eq.simplify()))) 
display(Math('q='+sym.latex(sym.solve(eq,q))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [9]:
# 2)
eq = 2*q + 3*q**2 - 5/q - 4/q**3

display(Math(sym.latex(eq)))
display(Math(sym.latex(sym.simplify(eq))))
display(Math(sym.latex(sym.cancel(eq)))) # puts into p/q form with integer coefficients

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [10]:
# 3)
# simplify this expression. confirm on your own using paper-and-pencil
expr = (sym.sqrt(3) + sym.sqrt(15)*q) / (sym.sqrt(2) + sym.sqrt(10)*q)
display(Math(sym.latex(expr)))
display(Math(sym.latex(sym.simplify(expr))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [11]:
sym.simplify( expr.subs(q,10) )

sqrt(6)/2

In [12]:
expr.subs(q,10).evalf()

1.22474487139159

## 2 Expanding terms

In [13]:
# define our terms
from sympy.abc import x

term1 = (4*x + 5)
term2 = x

print( term1*term2 )
print( sym.expand(term1*term2) )
print( Math(sym.latex(sym.expand(term1*term2)) ))

x*(4*x + 5)
4*x**2 + 5*x
<IPython.core.display.Math object>


In [14]:
term3 = x - 7 # note that parentheses are not necessary!

display(Math( sym.latex(term1*term3) ))
display(Math( sym.latex( sym.expand(term1*term3) )))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [15]:
# with two variables
y = sym.symbols('y')

expr = x*(2*y**2 - 5**x/x)
sym.expand(expr)

-5**x + 2*x*y**2

In [16]:
# three expressions and three variables!!
# but first, what variables have we already created??
%whos


Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
autopep8   module      <module 'autopep8' from '<...>te-packages/autopep8.py'>
display    function    <function display at 0x7f05685841e0>
eq         Add         3*q**2 + 2*q - 5/q - 4/q**3
expr       Mul         x*(-5**x/x + 2*y**2)
i          int         1
json       module      <module 'json' from '/hom<...>hon3.6/json/__init__.py'>
np         module      <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
q          Symbol      q
sol        list        n=2
sym        module      <module 'sympy' from '/ho<...>kages/sympy/__init__.py'>
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
x          Symbol      x
y          Symbol      y


In [17]:
z = sym.symbols('z')

term1 = (3 + x)
term2 = (y - 4*z)
term3 = (5/z + 3*x)

display(Math(sym.latex(term1*term2*term3)))
display(Math(sym.latex(sym.expand(term1*term2*term3))))
display(Math(sym.latex(sym.simplify(sym.expand(term1*term2*term3)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### 2.1 Exercises

In [18]:
# a function of two variables
Fxy = (4+x)*(2-y)
print(Fxy.subs({x:2,y:-2}))

24


In [19]:
numrange = range(0,3)
for i in numrange:
    for j in numrange:
        print('When x=%g and y=%g, f(x,y)=%g' %(i,j,Fxy.subs({x:i,y:j})) )

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


## 3 Creating and accessing matrices with numpy

In [20]:
A = np.array( [ [1,2],[3,4] ] )
print(A)

# make it look nicer
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [21]:
# initializing a matrix with zeros

numrange = range(0,5)

mat = np.zeros([len(numrange),len(numrange)])
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# populating matrices using row-col indexing

mat[0,1] = 1
# mat[5,8] = 4
mat

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
# can also use variables for indices
i = 2
j = 1
mat[i,j] = 4.5

display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [24]:
# now use a for-loop

numrange = range(0,3)
for i in numrange:
    for j in numrange:
        mat[i][j] = (-1)**(i+j)

mat

array([[ 1., -1.,  1.,  0.,  0.],
       [-1.,  1., -1.,  0.,  0.],
       [ 1., -1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### 3.1 Exercise

In [25]:
x,y = sym.symbols('x y')
Fxy = (4+x)*(2-y)

numrange = range(0,3)

funout = np.zeros((len(numrange),len(numrange)))

for i in numrange:
    for j in numrange:
        funout[i,j] = Fxy.subs({x:i,y:j})

display(Math(sym.latex(sym.sympify(funout))))

<IPython.core.display.Math object>

### 3.2 Exercise: Create a multiplication table

In [26]:
nums = range(1,11)

multmat = np.zeros((len(nums),len(nums)),dtype=int)

for i in nums:
    for j in nums:
        multmat[i-1,j-1] = i*j

        
display(Math(sym.latex(sym.sympify(multmat)))) # no display without display

x = 3

<IPython.core.display.Math object>

## 4 Associative, commutative, and distributive properties

### 4.1 Associative

In [27]:
from sympy.abc import x,y

expr1 = x*(4*y)
expr2 = (x*4)*y

# show that two equations are equal by subtracting them!
expr1 - expr2

0

### 4.2 Commutative

In [28]:
# create three expressions
e1 = x*4*y
e2 = 4*x*y
e3 = y*x*4

In [29]:
# quick reminder about substitution in sympy
display( e1.subs(x,3) )

# multiple subsitutions
e3.subs({x:2,y:3})

12*y

24

In [30]:
# now back to the task!
print( e1.subs({x:3,y:4}) )
print( e2.subs({x:3,y:4}) )
print( e3.subs({x:3,y:4}) )

48
48
48


### 4.3 Distributive

In [31]:
# another way of creating symbolic variables
from sympy.abc import a, b, c, d

expr = (a+b)*(c+d)
expr

(a + b)*(c + d)

In [32]:
sym.expand(expr)

a*c + a*d + b*c + b*d

In [33]:
sym.expand( (a+d)*(a-d) )

a**2 - d**2

In [34]:
# embedding expressions
a,x,y,z = sym.symbols('a,x,y,z')

x = 3*y + z
a = 4*x

display(a)

12*y + 4*z

### 4.4 Exercises

In [35]:
# with these two expressions, show that the commutative rule applies

w,x,y,z = sym.symbols('w,x,y,z')

x = w*(4-w)+1/w**2*(1+w)
expr1 = x*(y+z)
expr2 = 3/x+x**2

display(Math(sym.latex(expr1*expr2)))
display(Math(sym.latex(sym.simplify(expr1*expr2))))
display(Math(sym.latex(expr2*expr1 - expr1*expr2)))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## 5 Creating and working with Python lists

In [36]:
# a list is a collection of things, and created using brackets []
# A simple example is a list of numbers

lst = [1,3,4,7]
print( lst )
print(type(lst))

[1, 3, 4, 7]
<class 'list'>


In [37]:
# you can access individual list elements
lst[2]

4

In [38]:
# -1 is for the final element
lst[-1]

7

In [39]:
# "slicing"

# print the first N list items
N = 2
lst[:N]


[1, 3]

In [40]:
# print the last k items
k = 2
lst[-k:]


[4, 7]

In [41]:
# print items n through k
lst = [1,2,3,4,5,6,7,8,9]

n = 3
k = 7

lst[n-1:k]


[3, 4, 5, 6, 7]

In [42]:
# a list of strings
name = ['hello','my','name','is','Mike']

# access each element using a for-loop
for i in range(len(name)):
    print(name[i])

hello
my
name
is
Mike


In [43]:
# simpler!
for i in name:
    print(i)

hello
my
name
is
Mike


In [44]:
# lists can also hold more than one variable type
alist = [1,2,'cookies',[4,5]]

for i in alist:
    print(i)

1
2
cookies
[4, 5]


In [45]:
# getting items from a list-within-a-list

print( alist[-1] )

print( alist[-1][1] )

[4, 5]
5


In [46]:
# the term 'list' is reserved:
alist2 = list( (1,2,'cookies',[4,5]) )

for i in alist2:
    print(i)

1
2
cookies
[4, 5]


In [47]:
# importantly, we will use lists for sympy expressions!
# list_of_expressions
expr_list = [ 4*x**2 , 3+x , (1-x)/(1+x) ]

### 5.1 Exercises

In [48]:
# use sympy to expand and simplify these expressions
x = sym.symbols('x')

e1 = 2*x + x*(4-6*x) + x
e2 = -x * (2/x + 4/(x**2)) + (4+x)/(4*x)
e3 = (x + 3)*(x-3)*x*(1/(9*x))

# make a list of the expressions
exprs = [e1,e2,e3]

for i in range(0,3):
    display(Math('%s \\quad \\Longleftrightarrow \\quad %s' %(sym.latex(exprs[i]),sym.latex(sym.expand(exprs[i])))))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## 6 More on "slicing" in Python

In [49]:
# create an array (vector) of numbers
vec = [10,11,12,13,14,15,16,17,18,19,20]
# or
vec = list(range(10,21))

print(vec)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [50]:
# indexing a single item
vec[2]

12

In [51]:
# indexing multiple items (aka slicing)
vec[2:4]

[12, 13]

In [52]:
# from one element to the end
vec[4:]

[14, 15, 16, 17, 18, 19, 20]

In [53]:
# from the first element to a specific element
vec[:3]

[10, 11, 12]

In [54]:
# the last element
vec[-1]

# penultimate element
vec[-2]


19

In [55]:
# from the end to the beginning
vec[::-1]

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]

In [56]:
# with non-1 stepping
vec[0:5:2]

[10, 12, 14]

## 7 Greatest common denominator

In [57]:
# reminder: GCD is the largest integer that can divide both numbers without a remainder

# we'll use the math package for this!
import math

math.gcd(95,100)

5

In [58]:
math.gcd(0,3)

3

In [59]:
# application: reduce fraction to lowest term

a = 16
b = 88

fact = math.gcd(a,b)

display(Math('\\frac{%g}{%g} \\quad = \\quad \\frac{%g}{%g} \\times \\frac{%g}{%g}' %(a,b,a/fact,b/fact,fact,fact)))


<IPython.core.display.Math object>

### 7.1 Exercises

In [60]:
# show this property using symbols, and give an example with numbers.

# gcd(m·a, m·b) = m·gcd(a, b)

a,b,c = sym.symbols('a,b,c')

display( sym.gcd(c*a,c*b) )
display( c*sym.gcd(a,b) )


# now with real numbers
a = 5
b = 6
c = 7
display( math.gcd(c*a,c*b) )
display( c*math.gcd(a,b))


c

c

7

7

In [61]:
# double loop and store in matrix
import numpy as np

N = 10
gcdMat = np.zeros((10,15))+99

for i in range(0,10):
    for j in range(0,15):
        gcdMat[i,j] = math.gcd(i+1,j+1)
        
display(Math(sym.latex(sym.sympify(gcdMat))))

<IPython.core.display.Math object>

## 8 Introduction to dictionaries

In [62]:
# create a dictionary
D = dict(fruit=['banana','apple'],numbers=[1,3,4,2,5])

print(D)

{'fruit': ['banana', 'apple'], 'numbers': [1, 3, 4, 2, 5]}


In [63]:
# list the "keys"
D.keys()

dict_keys(['fruit', 'numbers'])

In [64]:
# get the information from the numbers
D['numbers']

[1, 3, 4, 2, 5]

In [65]:
# or this way
D.get('fruit')[0]

'banana'

In [66]:
len(D)

2

In [67]:
# print out all information in a loop!
for items in D.keys(): # .keys() is implied!
    print(D[items])

['banana', 'apple']
[1, 3, 4, 2, 5]


In [68]:
# make a dictionary of equations
x,y = sym.symbols('x,y')

D = dict(eqsWithX=[x/3-6,x*2+3],eqsWithY=[y-y/4,y-5])
D.keys()

Dkeys = list(D)

# access individual keys
D[Dkeys[0]]


[x/3 - 6, 2*x + 3]

### 8.1 Exercise

In [69]:
# let's make a new dictionary
x,y = sym.symbols('x,y')

# count number of x's and y's in the equation
D = dict(eqsWithX=[4*x-6,x**2-9],eqsWithY=[sym.sin(y)])

# solve them in a loop
for keyi in D:
    
    print('Equations solving for ' + keyi[-1] + ':')
    
    for i in D[keyi]:
        
        fullEQ     = sym.latex(sym.sympify(i)) + ' = 0'
        middlepart = '\\quad\\quad \\Rightarrow\\quad\\quad ' + keyi[-1] + ' = '
        soln       = sym.latex(sym.solve(i))
        
        display(Math( '\\quad\\quad ' + fullEQ + middlepart + soln ))



Equations solving for X:


<IPython.core.display.Math object>

<IPython.core.display.Math object>

Equations solving for Y:


<IPython.core.display.Math object>

## 9 Prime factorization

In [70]:
# factor an integer into the product of prime numbers
number = 48

# Use the sympy function factorint. The output is a dictionary!
fact_dict = sym.factorint(number)
print(fact_dict)

{2: 4, 3: 1}


In [71]:
# just print the prime numbers
primenumbers = list( fact_dict.keys() )

print('The prime factors of ' + str(number) + ' are ' + str(primenumbers))

fact_dict[primenumbers[1]]

The prime factors of 48 are [2, 3]


1

In [72]:
# test on prime number
sym.factorint(4)

{2: 2}

### 9.1 Exercise

In [73]:
# loop through numbers and report whether each number is composite or prime

nums = range(2,51)
for i in nums:
    di = sym.factorint(i)
    ks = list(di.keys())
    if len(di)==1 and di[ks[0]]==1:
        print('%s is a prime number' %i)
    else:
        print('%s is a composite number with prime factors %s' %(i,list(di.keys())))


2 is a prime number
3 is a prime number
4 is a composite number with prime factors [2]
5 is a prime number
6 is a composite number with prime factors [2, 3]
7 is a prime number
8 is a composite number with prime factors [2]
9 is a composite number with prime factors [3]
10 is a composite number with prime factors [2, 5]
11 is a prime number
12 is a composite number with prime factors [2, 3]
13 is a prime number
14 is a composite number with prime factors [2, 7]
15 is a composite number with prime factors [3, 5]
16 is a composite number with prime factors [2]
17 is a prime number
18 is a composite number with prime factors [2, 3]
19 is a prime number
20 is a composite number with prime factors [2, 5]
21 is a composite number with prime factors [3, 7]
22 is a composite number with prime factors [2, 11]
23 is a prime number
24 is a composite number with prime factors [2, 3]
25 is a composite number with prime factors [5]
26 is a composite number with prime factors [2, 13]
27 is a composit

## 10 Solving inequalities

In [74]:
x = sym.symbols('x')

expr = 4*x > 8
sym.solve(expr)

(2 < x) & (x < oo)

In [75]:
display(Math(sym.latex(sym.solve(expr))))

<IPython.core.display.Math object>

In [76]:
sym.oo > 10000093847529345

True

In [77]:
expr = (x-1)*(x+3) > 0

display(Math(sym.latex(sym.solve(expr))))

<IPython.core.display.Math object>

In [78]:
# sym.solve will return the expression if not enough information

a,b,c = sym.symbols('a,b,c')

expr = a*x > b**2/c
display(Math(sym.latex(expr)))

try:
    sym.solve(expr)#,x
except Exception as E:
    print("Exception: {}".format(type(E).__name__), E)

<IPython.core.display.Math object>

Exception: NotImplementedError 
inequality has more than one symbol of interest.


In [79]:
# a slightly richer problem
sym.solve( 2*x**2>8 )

((-oo < x) & (x < -2)) | ((2 < x) & (x < oo))

### 10.1 Exercise

In [80]:
expr = (3*x/2) + (4-5*x)/3 <= 2 - (5*(2-x))/4

display(Math(sym.latex(expr)))
sym.solve(expr)

<IPython.core.display.Math object>

(22/17 <= x) & (x < oo)

## 11 Adding polynomials

In [81]:
from sympy.abc import x

# straight-forward version
p1 = 2*x**3 + x**2 - x
p2 = x**3 - x**4 - 4*x**2
print( p1+p2 )

display(Math('(%s) + (%s) \quad=\quad (%s)' %(sym.latex(p1),sym.latex(p2),sym.latex(p1+p2) )))

-x**4 + 3*x**3 - 3*x**2 - x


<IPython.core.display.Math object>

In [82]:
# Using the Poly class
p1 = sym.Poly(2*x**6 + x**2 - x)

p1

Poly(2*x**6 + x**2 - x, x, domain='ZZ')

In [83]:
# can implement several methods on the polynomial object
print( p1.eval(10) )

print( p1.degree() )

2000090
6


In [84]:
# create a second polynomial
p2 = sym.Poly(x**3 - x**4 - .4*x**2)
print( p1-p2 )

# can also call the add method on the polynomial objects
p1.add(p2)
p1.sub(p2)
print(p1.sub(p2))
print(p1)


Poly(2.0*x**6 + 1.0*x**4 - 1.0*x**3 + 1.4*x**2 - 1.0*x, x, domain='RR')
Poly(2.0*x**6 + 1.0*x**4 - 1.0*x**3 + 1.4*x**2 - 1.0*x, x, domain='RR')
Poly(2*x**6 + x**2 - x, x, domain='ZZ')


### 11.1 Exercise

In [85]:
# create a list of polynomials
# loop through. if order is even, sum the coeffs. if order is odd, count the number of coeffs

polys = [ sym.Poly(2*x + x**2), sym.Poly(-x**3 + 4*x), sym.Poly(x**5-x**4+1/4*x+4) ]

for poli in polys:
    if poli.degree()%2==0:
        print('The degree of %s is even, and the coefficients sum to %s.' %(poli.as_expr(),sum(poli.coeffs())))
    else:
        print('The degree of %s is odd, and there are %s coefficients.' %(poli.as_expr(),len(poli.coeffs())))

The degree of x**2 + 2*x is even, and the coefficients sum to 3.
The degree of -x**3 + 4*x is odd, and there are 2 coefficients.
The degree of 1.0*x**5 - 1.0*x**4 + 0.25*x + 4.0 is odd, and there are 4 coefficients.


## 12 Multiplying polynomials

In [86]:
x = sym.symbols('x')

x**2 * x**3

x**5

In [87]:
# a litte more complicated
p1 = 4*x**2 - 2*x
p2 = x**3 + 1

p1*p2

(4*x**2 - 2*x)*(x**3 + 1)

In [88]:
# the way your math teacher would want it written out
print( sym.expand( p1*p2 ) )

display(Math(sym.latex(p1*p2)))
display(Math(sym.latex(sym.expand(p1*p2))))


4*x**5 - 2*x**4 + 4*x**2 - 2*x


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [89]:
# check our work from the slides!
x,y = sym.symbols('x,y')

poly1 = x**5 + 2*x*y + y**2
poly2 = x - 3*x*y

poly1*poly2

(-3*x*y + x)*(x**5 + 2*x*y + y**2)

In [90]:
display(Math(sym.latex(sym.expand( poly1*poly2 ))))

<IPython.core.display.Math object>

### 12.1 Exercise

In [91]:
# with x's and y's, substitute before vs after multiplication
x,y = sym.symbols('x,y')

fxy = 4*x**4 - 9*y**3 - 3*x**2 + x*y**2
gxy = 4/5*y**3 - x**3 + 6*x**2*y

display(Math( '(%s)\quad\\times\quad(%s) \quad=\quad %s' %(sym.latex(fxy),sym.latex(gxy),sym.latex(sym.expand(fxy*gxy)) )))


<IPython.core.display.Math object>

In [92]:
xval = 5
yval = -2

# first substitute and then multiply
fxy_subs = fxy.subs({x:xval,y:yval})
gxy_subs = gxy.subs({x:xval,y:yval})
print('Separate substitution: %s' %(fxy_subs*gxy_subs))

# multiply then substitute
fg = (fxy*gxy).subs({x:xval,y:yval})
print('Multiplied substitution: %s' %fg)


Separate substitution: -1085833.80000000
Multiplied substitution: -1085833.80000000


## 13 Dividing by polynomials

In [93]:
p1 = 4*x**5 - x
p2 = 2*x**3-x

display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(p1/p2)) ))
display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(sym.expand(p1/p2))) ))
display(Math('\\frac{%s}{%s} = %s' %(sym.latex(p1),sym.latex(p2),sym.latex(sym.simplify(p1/p2))) ))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [94]:
# with two variables
x,y = sym.symbols('x,y')

pNum = x**3 + y**2 - 4*x**2*y + x*y + 4*y
pDen = x + y

display(Math('\\frac{%s}{%s} = %s' %(sym.latex(pNum),sym.latex(pDen),sym.latex(sym.simplify(pNum/pDen))) ))


<IPython.core.display.Math object>

### 13.1 Exercise

In [95]:
# first, a primer on sym.fraction

num = sym.sympify(3)/sym.sympify(4)
# num = sym.sympify(3/4)

finfo = sym.fraction(num)
print(type(finfo))
print(finfo[0])

# can also isolate the numerator separately
num = sym.fraction(num)[0]
print(num)

<class 'tuple'>
3
3


In [96]:

# use a loop to find the integer value of y that makes this equation simplify
pNum = x**6 + 2*x**4 + 6*x  - y
pDen = x**3 + 3


for i in range(5,16):
    
    pnum = pNum.subs({y:i})
    display(Math('\\frac{%s}{%s} = %s' %(sym.latex(pnum),sym.latex(pDen),sym.latex(sym.simplify(pnum/pDen))) ))
    
    if sym.fraction(sym.simplify(pnum/pDen))[1]==1:
        rightnumber = i

print( 'When y=%g, there is no denominator!' %rightnumber)


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

When y=9, there is no denominator!


## 14 Factoring polynomials

In [97]:
x,y = sym.symbols('x,y')

po = x**2 + 4*x + 3
sym.factor(po)

(x + 1)*(x + 3)

In [98]:
# with output

fac = sym.factor(po)
print(fac)

(x + 1)*(x + 3)


In [99]:
# not every polynomial can be factored!
po = x**2 + 4*x - 3

sym.factor(po)

x**2 + 4*x - 3

In [100]:
expr = 2*y**3 - 2*y**2 - 18*y + 18
sym.factor(expr)

2*(y - 3)*(y - 1)*(y + 3)

In [101]:
# multiple variables
expr = 2*x**3*y - 2*x**2*y**2 + 2*x**2*y + 6*x**2 - 6*x*y + 6*x
sym.factor(expr)


2*x*(x*y + 3)*(x - y + 1)

### 14.1 Exercise

In [102]:
# test whether factorable, print if so.

exprs = [ x**2+4*x+3 , 2*y**2-1 , 3*y**2+12*y ]

for expri in exprs:
    tmp = str( sym.factor(expri) )
    
    if tmp.find('(')!=-1:
        display(Math('%s \\quad\\Rightarrow\\quad %s' %(sym.latex(sym.expand(expri)),sym.latex(sym.factor(expri)))))
    else:
        display(Math('%s \\quad\\Rightarrow\\quad\\text{ not factorable!}' %sym.latex(sym.expand(expri))))
    

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## 15 Algebra 1 BUG HUNT!

In [103]:
# from sympy.abc import x2
x2 = sym.symbols('x2')

x2 = 4

In [104]:
a,b,c,d = sym.symbols('a,b,c,d')

expr = 4*b + 5*a*a - c**3 + 5*d


In [105]:
import math
math.gcd(30,50)

10

In [106]:
from sympy.abc import x

expr = 4*x - 8
sym.solve(expr)

[2]

In [107]:
import numpy as np

A = np.array( [ [1,2],[3,4] ] )
# make it look nice
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [108]:
fact_dict = sym.factorint(44)
allkeys = fact_dict.keys()

for i in fact_dict:
    print('%g was present %g times.' %(i,fact_dict[i]))


2 was present 2 times.
11 was present 1 times.


In [109]:
x,y = sym.symbols('x,y')

expr = 4*x - 5*y**2

expr.subs({x:5})


20 - 5*y**2

In [110]:
# goal is to show a fraction

f = sym.sympify(5)/9

display(Math(sym.latex(f)))


<IPython.core.display.Math object>

In [111]:
# print the last 3 items from a list
lst = [1,3,2,5,4,6,7,5,3,7]
lst[-3:]


[5, 3, 7]

In [112]:
from sympy.abc import x,y

expr = 2*x + 4*y

# solve for y
sym.solve(expr,y)

[-x/2]

In [113]:
import numpy as np

A = np.array( [ [1,2],[3,4] ] )

# set the element in the second row, second column to 9
A[1,1] = 9
print(A)

[[1 2]
 [3 9]]
